name: Build and push container

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - 
        name: Load environment from YAML
        uses: doughepi/yaml-env-action@v1.0.0
        with:
          files: settings.yaml
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: frontendversion=${{ env.FRONTENDVERSION }}
          push: true
          tags: viplab/standalone-frontend:latest,viplab/standalone-frontend:${{ env.FRONTENDVERSION }}-latest
